# Generated by Django 4.0.4 on 2023-07-28 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('nombreEmpleado', models.CharField(max_length=45, verbose_name='Nombre del empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('producto', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total', models.IntegerField(verbose_name='Stock')),
                ('precio_compra', models.FloatField(max_length=45, verbose_name='Precio de compra')),
                ('precio_venta', models.FloatField(max_length=20, verbose_name='Precio de venta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.categoria')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.proveedor')),
            ],
        ),
    ]
